apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USERNAME: bXl1c2Vy  # Base64 encoded value of "myuser"
  DB_PASSWORD: c2VjcmV0MTIz  # Base64 encoded value of "secret123"
