apiVersion: v1
kind: Service
metadata:
  name: secret-app
  labels:
    app: secret-app
spec:
  type: LoadBalancer
  selector:
    app: secret-app
  ports:
    - protocol: TCP
      port: 80          # External port to expose
      targetPort: 8080  # The port your app is running on inside the pod
