name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed  # Triggers only after the previous workflow completes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
            
            echo "Stopping and removing old container..."
            docker stop myapp || true
            docker rm myapp || true
            
            echo "Running new container on port 80..."
            docker run -d -p 80:8080 \
              -e SECRET_METHOD=env \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              --name myapp \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
            
            echo "Deployment successful!"
