name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed  # Triggers only after the previous workflow completes

jobs:
  deploy-to-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1

      - name: Configure Kubeconfig
        run: |
            mkdir -p $HOME/.kube  # Ensure the .kube directory exists
            echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
            chmod 600 $HOME/.kube/config
        env:
            KUBECONFIG: $HOME/.kube/config
        
      

      - name: Check Kubernetes Cluster Info
        run: kubectl cluster-info

      - name: Debug Kubernetes Context
        run: kubectl config view

      - name: Check Network Access
        run: kubectl get svc
      

      - name: Update Kubernetes Deployment
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl set image deployment/secret-app secret-app=dev9846/my-flask-app:${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/secret-app
